site_name: UseMe
site_author: botlaram
site_description: "this Mkdocs contains Python Modules, about Devops and Cheat Code"
repo_url: "https://github.com/botlaram"

nav:
- Home: index.md
- Cheat Code: cheat_code.md
- Python: python.md
- Linux: linux.md
- Computer Networking: networking.md
- DSA: dsa.md
- Devops Tools: devops_tools.md
- Azure: azure.md
- K8: kubernetes.md
- Publish: publish.md
- Devops Project: devops_projects.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.path
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - search.share
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
    primary: teal
    accent: lime
  font:
    text: Marmelad
    code: Roboto Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

plugins:
- search:
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/botlaram
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/ramakrishna-botla-772a8918b/

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list

copyright: |
  &copy; <a href="https://github.com/botlaram"  target="_blank" rel="noopener">botlar4</a>
